# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: maixu@umich.edu
author_name: maixu
has_binder: true
has_settings: true
kind: server
labextension_name: srs-jupyterlab-extension
project_short_description: A JupyterLab extension.
python_name: srs_jupyterlab_extension
repository: https://github.com/educational-technology-collective/srs-jupyterlab-extension
test: true
